CREATE TABLE "STAGE"."D_TERM" 
   (	 
	"TERM_CD" VARCHAR2(4 BYTE) NOT NULL, 
	"TERM_SD" VARCHAR2(10 BYTE) NOT NULL, 
	"TERM_LD" VARCHAR2(30 BYTE) NOT NULL, 
	"ACAD_YR_SID" NUMBER(10,0) NOT NULL ENABLE, 
	"TERM_BEGIN_DT" DATE, 
	"TERM_END_DT" DATE, 
	"TERM_CTGRY_CD" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"TERM_CTGRY_SD" VARCHAR2(10 BYTE) NOT NULL ENABLE
   )
